site_name: 小木个人笔记
site_description: '记录生活、技术，点点滴滴'
site_author: '小木'
docs_dir: docs/
repo_name: 'shengleiRain/shengleiRain.io'
repo_url: 'https://github.com/shengleiRain/shengleiRain.github.io'
edit_uri: ""

copyright: '&copy; 2020 小木'
theme:
  name: material
  static_templates:
    - 404.html
  palette:
    primary: 'white'
    accent: 'blue'
  font:
    text: Roboto
    code: Roboto Mono
  language: 'zh'
  feature:
    tabs: true
  logo: assets/images/favicon.ico
  favicon: assets/images/favicon.ico

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shengleiRain
  disqus: 'slblog'
  # manifest: manifest.webmanifest

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
  - 'js/baidu-tongji.js'
  - 'js/extras.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

google_analytics:
  - 'UA-155096376-1'
  - 'auto'

nav:
    - Home: index.md
    - Android: 
      - android/2020-06-04-material design.md
      - Kotlin:
        - android/kotlin/2020-03-11-标准函数总结.markdown
        - android/kotlin/2020-03-13-Kotlin协程（一）.md
        - android/kotlin/2020-03-13-Kotlin协程（二）.md
        - android/kotlin/2020-03-15-Kotlin协程（三）.md
    - Git:
      - git/2020-03-16-Git命令.md
      - git/2020-04-10-git branch, git checkout and git merge.md
      - git/2020-04-10-git pull vs git fetch.md
      - git/2020-04-10-Git重写历史.md
    - Network:
      - HTTP:
        - network/http/2020-04-16-HTTP协议总述.md
        - network/http/2020-08-03-详解HTTP.md
        - network/http/2020-08-03-URL、URN和URI.md
    - Others:
      - others/2020-03-12-gradle-aliyun-代理.md
      - others/2020-03-14-Android项目的gradle依赖路径记录.md
      - others/2020-04-06-SSH.md
      - others/2020-04-08-Vi.md
      - others/2020-04-11-加盐密码哈希.md
      - others/2020-06-06-flask+uwsgi后台搭建.md

